
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: .
 
- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --name "udapeople-backend" start
    
   
- name: Start pm2
  become: true
  command: pm2 start /server.js --name node-app
