version: 2.1

orbs:
  slack: circleci/slack@4.10.1
  

commands:
    destroy-environment:
      description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
      parameters:
        workflowID:
          type: string
          default: ${CIRCLE_WORKFLOW_ID:0:7}
      steps:
        - run:
            name: Destroy environments
            when: on_fail
            command: |
              #aws s3 rb s3://udapeople-872734010489 --force  
              aws --region us-east-1 cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflowID>>
              #aws --region us-east-1 cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflowID>>
jobs:
    build-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Build front-end
            command: |
              cd frontend
              npm install
              npm run build
        - save_cache:
            paths: [frontend/node_modules]
            key: frontend-build
  
    build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              cd backend
              npm install
              npm fund
              npm run build
        - save_cache:
            paths: [backend/node_modules]
            key: backend-build
            
    test-frontend:
        docker:
        - image: circleci/node:13.8.0
        steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Test front-end
            command: |
              cd frontend
              npm install
              npm run test
            
    test-backend:
        docker:
        - image: circleci/node:13.8.0
        steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Test back-end
            command: |
              cd backend
              npm install
              npm run test
    scan-frontend:
        docker:
        - image: circleci/node:13.8.0
        steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Scan front-end
            command: |
              cd frontend
              npm install
              npm audit fix --audit-level=critical --force
              npm audit --audit-level=critical
    scan-backend:
        docker:
        - image: circleci/node:13.8.0
        steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Scan back-end
            command: |
              cd backend
              npm install
              npm audit fix --audit-level=critical --force
              npm audit fix --audit-level=critical --force
              npm audit --audit-level=critical
        - slack/notify:
            event: fail
            mentions: '@Salma Ibraheem'
            template: basic_fail_1
            channel: $SLACK_DEFAULT_CHANNEL
            
    deploy-infrastructure:
        docker:
        - image: amazon/aws-cli
        steps:
        - checkout
        - run:
            name: INstall gzip and tar to handle (Error tar utility is not present in this image but it is required. Please install it to have workflow workspace capability)
            command:  |
              yum -y install tar gzip
        - run:
            name: Ensure back-end infrastructure exists
            command: |
              aws cloudformation deploy \
                --template-file .circleci/files/backend.yml \
                --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
    #    - run:
    #        name: Ensure front-end infrastructure exist
    #        command: |
    #          aws cloudformation deploy \
    #            --template-file .circleci/files/frontend.yml \
    #            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
    #            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
        - run:
            name: Add back-end ip to ansible inventory
            command: |
              BACKEND_PUBLIC_IP=$(aws --region us-east-1 ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
              echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
              cat .circleci/ansible/inventory.txt
        - persist_to_workspace:
            root: ~/
            paths:
            - project/.circleci/ansible/inventory.txt
        - destroy-environment    
        
    configure-infrastructure:
        docker:
          - image: python:3.7-alpine3.11
        steps:
          - checkout
          - add_ssh_keys:
              fingerprints: ["04:74:91:0e:50:f7:c7:68:1a:dc:2c:2f:b2:03:c7:8d"] 
          - attach_workspace:
              at: ~/
          - run:
              name: Install dependencies
              command: |
                apk add --update tar gzip
                pip install awscli
                apk add --update ansible 
                
          - run:
              name: Configure server
              command: |
                cat ./.circleci/ansible/inventory.txt
                export ANSIBLE_HOST_KEY_CHECKING=False
                export RECORD_HOST_KEYS=False
                export ANSIBLE_PARAMIKO_BANNER_TIMEOUT=30   
                echo ENVIROMENT=production > "backend/.env"      
                echo TYPEORM_CONNECTION=postgres >> "backend/.env"
                echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
                echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"          
                echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"      
                echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"            
                echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"      
                echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"     
                echo "CONTENT OF backend/.env"      
                cat backend/.env         
                cd .circleci/ansible
                ansible-playbook -i inventory.txt configure-server.yml -v 
          - destroy-environment 
          
    run-migrations:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - run:
              name: Run migrations
              command: |
                cd backend
                npm install
                npm run migrations > migrations_dump.txt
                cat migrations_dump.txt
          - run:
              name: Send migration results to memstash
              command: |
                if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
                then
                    # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
                    curl https://kvdb.io/UnQcetmSsv4ocWVGvfed29/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
                fi
          - destroy-environment    

workflows:
    default:
        jobs:
        - deploy-infrastructure
        #- build-frontend
        #- build-backend
        #- test-frontend:
        #    requires:
        #        - build-frontend
        #- test-backend:
        #    requires:
        #        - build-backend
        #- scan-frontend:
        #    requires:
        #        - build-frontend
        #- scan-backend:
        #    requires:
        #        - build-backend
        #- deploy-infrastructure
            #requires: [test-backend]
            #requires: [test-frontend, test-backend, scan-frontend, scan-backend]
        - configure-infrastructure:
            requires: [deploy-infrastructure]
        - run-migrations:
            requires: [configure-infrastructure]
            
